[package]
name = "mcp_server_context7"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/mcp_server_context7.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.3.0"
